version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: dev_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - card-nexus-data:/var/lib/postgresql/data

  test_db:
    image: postgis/postgis:15-3.3
    container_name: test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test-card-nexus-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  card-nexus-data:
  test-card-nexus-data:
